import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const initialData = {
  name: 'Aiman Rahman', role: 'Software Engineering Student',
  heroTitle: 'Building quiet systems for loud ideas.',
  heroSub: 'I turn curiosity into useful interfaces, resilient code, and small moments that feel inevitable.',
  heroVideo: 'https://cdn.coverr.co/videos/coverr-a-city-at-night-1571/1080p.mp4',
  location: 'Selangor, Malaysia', education: 'B.Sc. Software Engineering · Year 1', gpa: 'Current CGPA · 3.82 / 4.00',
  email: 'hello@aimanrahman.dev', phone: '+60 12 345 6789', github: 'github.com/aimanrahman',
  about: 'I am a first-year software engineering student drawn to the space between logical systems and human behaviour. I care about clarity, details, and products that quietly make life easier.',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85',
  projects: [
    { title: 'OASIS', type: 'Campus wellbeing platform', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1400&q=85', desc: 'A thoughtful digital companion for students navigating busy semesters.' },
    { title: 'THREAD / 01', type: 'Full-stack social archive', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85', desc: 'Capturing small memories in a connected, searchable private space.' },
    { title: 'SIGNAL', type: 'Data visualisation experiment', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85', desc: 'Turning complex campus data into a calm, readable interface.' }
  ],
  skills: [ ['01', 'Frontend Systems', 'React, TypeScript, responsive interfaces'], ['02', 'Backend Foundations', 'Node.js, REST APIs, relational databases'], ['03', 'Product Thinking', 'Research, wireframes, interaction design'], ['04', 'Creative Coding', 'Data, motion, generative experiments'] ],
  competitions: [
    { title: 'Hackathon 2025', result: 'Top 10 Finalist', image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1100&q=85' },
    { title: 'Code Sprint', result: 'Best UI / UX', image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1100&q=85' },
    { title: 'Innovation Challenge', result: 'Participant', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1100&q=85' }
  ]
};
const password = 'atlas2026';
const load = () => { try { return { ...initialData, ...JSON.parse(localStorage.getItem('atlas-data')) }; } catch { return initialData; } };
function App(){
 const [data,setData]=useState(load), [editor,setEditor]=useState(false), [login,setLogin]=useState(false), [pass,setPass]=useState(''), [toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem('atlas-data',JSON.stringify(data)),[data]);
 const update=(key,value)=>setData(d=>({...d,[key]:value}));
 const save=()=>{setToast('Changes saved locally');setTimeout(()=>setToast(''),2200)};
 const add=(key,item)=>update(key,[...data[key],item]);
 return <><header><a className="brand" href="#top">AR<span>·</span></a><nav><a href="#about">About</a><a href="#work">Work</a><a href="#lab">Lab</a><a href="#contact">Contact</a></nav><button className="ghost" onClick={()=>editor?setEditor(false):setLogin(true)}>{editor?'Close editor':'Edit site ↗'}</button></header>
 <main id="top">
 <section className="hero"><video autoPlay muted loop playsInline src={data.heroVideo}/><div className="scrim"/><div className="orb"/><div className="hero-content"><p className="eyebrow">{data.role} · {data.location}</p><h1>{data.heroTitle}</h1><p className="hero-copy">{data.heroSub}</p><a className="button" href={'mailto:'+data.email}>Let’s talk <b>↗</b></a></div><p className="scroll">SCROLL TO EXPLORE <i/></p></section>
 <section id="about" className="about section"><div className="section-label">01 / PROFILE</div><div className="about-grid"><div className="portrait"><img src={data.avatar}/><span>Based in<br/>Malaysia</span></div><div><p className="kicker">THE PERSON BEHIND THE PIXELS</p><h2>Not just writing code.<br/><em>Designing a point of view.</em></h2><p className="about-copy">{data.about}</p><div className="facts"><span>FROM <b>{data.location}</b></span><span>STUDYING <b>{data.education}</b></span><span>ACADEMIC <b>{data.gpa}</b></span></div><div className="contact-row"><a href={'mailto:'+data.email}>{data.email}</a><a href={'https://'+data.github}>{data.github} ↗</a></div></div></div></section>
 <section id="work" className="work section"><div className="section-label">02 / SELECTED WORK</div><div className="title-line"><h2>Proof, not promises.</h2><p>A selection of student projects in progress—built to learn in public and solve with intent.</p></div><div className="projects">{data.projects.map((p,i)=><article className={'project p'+i} key={p.title+i}><img src={p.image}/><div className="project-shade"/><div><p>{p.type}</p><h3>{p.title}</h3><span>{p.desc}</span></div><i>↗</i></article>)}</div></section>
 <section id="lab" className="skills section"><div className="section-label">03 / PERSONAL TOOLKIT</div><h2>Useful across the stack.<br/><em>Restlessly unfinished.</em></h2><div className="skill-grid">{data.skills.map((s,i)=><article key={s[0]+i}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><b>→</b></article>)}</div></section>
 <section className="competition section"><div className="section-label">04 / COMPETITION LOG</div><div className="competition-heading"><h2>Made under<br/>pressure.</h2><p>Every deadline taught me something worth keeping: collaboration, momentum, and the courage to show unfinished work.</p></div><div className="mosaic">{data.competitions.map((c,i)=><article className={'tile t'+i} key={c.title+i}><img src={c.image}/><div><p>{c.result}</p><h3>{c.title}</h3></div></article>)}<article className="tile note"><span>+ {data.competitions.length}</span><p>competitions and counting</p><b>2025 — now</b></article></div></section>
 <section id="contact" className="closing"><div><p className="eyebrow">AVAILABLE FOR COLLABORATION / INTERNSHIPS</p><h2>Have an idea<br/>worth making?</h2><a href={'mailto:'+data.email} className="button">Start a conversation <b>↗</b></a></div><div className="closing-bottom"><span>© 2026 {data.name}</span><span>{data.location}</span><a href={'mailto:'+data.email}>{data.email}</a></div></section>
 </main>
 {login&&<div className="modal"><form onSubmit={e=>{e.preventDefault();if(pass===password){setEditor(true);setLogin(false);setPass('')}else setToast('Incorrect password')}}><button type="button" className="x" onClick={()=>setLogin(false)}>×</button><p className="eyebrow">HOST ACCESS</p><h3>Enter your password.</h3><input autoFocus type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password"/><button className="button">Unlock editor ↗</button><small>Demo password: atlas2026<br/>Change the password constant in src/main.jsx before launch.</small></form></div>}
 {editor&&<aside className="editor"><div><p className="eyebrow">HOST MODE</p><h3>Content editor</h3><button className="x" onClick={()=>setEditor(false)}>×</button></div><label>Name<input value={data.name} onChange={e=>update('name',e.target.value)}/></label><label>Role<input value={data.role} onChange={e=>update('role',e.target.value)}/></label><label>State / Country<input value={data.location} onChange={e=>update('location',e.target.value)}/></label><label>Education<input value={data.education} onChange={e=>update('education',e.target.value)}/></label><label>CGPA<input value={data.gpa} onChange={e=>update('gpa',e.target.value)}/></label><label>Hero title<textarea value={data.heroTitle} onChange={e=>update('heroTitle',e.target.value)}/></label><label>Hero subtitle<textarea value={data.heroSub} onChange={e=>update('heroSub',e.target.value)}/></label><label>Intro<textarea value={data.about} onChange={e=>update('about',e.target.value)}/></label><label>Email<input value={data.email} onChange={e=>update('email',e.target.value)}/></label><label>Phone<input value={data.phone} onChange={e=>update('phone',e.target.value)}/></label><label>GitHub<input value={data.github} onChange={e=>update('github',e.target.value)}/></label><label>Hero video URL<input value={data.heroVideo} onChange={e=>update('heroVideo',e.target.value)}/></label><label>Portrait URL<input value={data.avatar} onChange={e=>update('avatar',e.target.value)}/></label><EditList title="Projects" items={data.projects} fields={['title','type','desc','image']} onChange={x=>update('projects',x)} onAdd={()=>add('projects',{title:'NEW PROJECT',type:'Project type',desc:'A short project description.',image:data.projects[0].image})}/><SkillEdit items={data.skills} onChange={x=>update('skills',x)}/><EditList title="Competitions" items={data.competitions} fields={['title','result','image']} onChange={x=>update('competitions',x)} onAdd={()=>add('competitions',{title:'New Competition',result:'Achievement',image:data.competitions[0].image})}/><button className="save" onClick={save}>Save changes</button><button className="reset" onClick={()=>{localStorage.removeItem('atlas-data');setData(initialData)}}>Reset to starter content</button></aside>}
 {toast&&<div className="toast">{toast}</div>}</> }
function EditList({title,items,fields,onChange,onAdd}){const change=(i,k,v)=>onChange(items.map((x,n)=>n===i?{...x,[k]:v}:x));return <div className="edit-list"><h4>{title}</h4>{items.map((item,i)=><div className="list-item" key={i}>{fields.map(f=><label key={f}>{f}<input value={item[f]} onChange={e=>change(i,f,e.target.value)}/></label>)}<button onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div>)}<button className="add" onClick={onAdd}>+ Add {title.slice(0,-1)}</button></div>}
function SkillEdit({items,onChange}){const change=(i,k,v)=>onChange(items.map((x,n)=>n===i?x.map((y,m)=>m===k?v:y):x));return <div className="edit-list"><h4>Skills</h4>{items.map((item,i)=><div className="list-item" key={i}>{['number','title','description'].map((f,k)=><label key={f}>{f}<input value={item[k]} onChange={e=>change(i,k,e.target.value)}/></label>)}<button onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div>)}<button className="add" onClick={()=>onChange([...items,[String(items.length+1).padStart(2,'0'),'New Skill','Describe your strength here']])}>+ Add Skill</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
